version: "3.8"

services:
  website:
    build: .
    container_name: dev-website
    environment:
      - JEKYLL_ENV=development
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
